data:
  filename: null
  batch_size: 1
  length: null
  p: null
  num_threads: 4
  max_queue_length: 16

model:
  ch: 16
  depth: 8
  num_blocks: 2
  kernel_size: 3
  embedding_dim: 16

optimizer:
  type: adam
  learning_rate: 1e-3
  b1: 0.9
  b2: 0.999
  eps: 1e-5

training:
  num_iters: 100000
  log_interval: 100

validation:
  interval: 1000
  num_steps: 100
  length: 16384
  padded: true

rngs:
  init: 1
  data: 2
  val: 3
